services:
  postgres:
    image: postgres:16-alpine
    container_name: titan-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Frfgekmrj391
      POSTGRES_DB: chatGPT
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5-community
    container_name: titan-neo4j
    environment:
      NEO4J_AUTH: neo4j/Frfgekmrj391
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_auth__minimum__password__length: 5
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "Frfgekmrj391", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: titan-redis-dbs
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres-data:
  neo4j-data:
  neo4j-logs:
  redis-data:
