vector_db:
  dsn: postgresql://postgres:Frfgekmrj391@localhost:5432/chatGPT

graph_db:
  uri: bolt://localhost:7687
  user: neo4j
  password: Frfgekmrj391

redis:
  url: redis://localhost:6379/1  # Используем DB 1 для памяти
  ttl_hours: 24
  max_recent: 200

# Memory evaluation settings
importance_threshold: 0.65  # Вернули обратно для ML evaluator
gc_threshold: 0.25
embedding_model: text-embedding-3-small

# Importance weights (customizable)
importance_weights:
  personal: 1.0
  technical: 0.9
  temporal: 0.9
  emotional: 0.7
  correction: 1.1
  plans: 0.9

# API settings
api_host: 0.0.0.0
api_port: 8001

# Event Bus integration
event_bus_url: redis://localhost:6379/0
consumer_group: memory-service

# Observability
metrics_port: 8002
trace_sample_rate: 0.1
