global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'titan-eventbus'
    static_configs:
      - targets: ['titan-eventbus:8000']
        labels:
          service: 'eventbus'
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
